version: "3.9"

services:
    ssr-app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        depends_on:
            - postgres
        ports:
            - "5000:5000"
        volumes:
            # что бы слушать файлы
            - ./SSR-frontend:/server
        env_file: development.env
        networks:
            - main-networks
        restart: always

    postgres:
        image: postgres:12
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        env_file: development.env
        networks:
            - main-networks
        restart: always

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.18
        env_file: development.env
        ports:
            - "8080:80"
        volumes:
            - ./pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - main-networks
        restart: always

networks:
    main-networks:
        driver: bridge
