FROM node:14

WORKDIR /server

COPY ./package*.json .
RUN npm install

COPY . .

EXPOSE 5000

# env указал на самом хероку
#ENV NODE_ENV=development
#ENV HTTP_PROTOCOL=http
#ENV PORT=5000
#ENV DATABASE_URL=postgres://postgresUser:newPassword@postgres:5432/fargo-cards

RUN npm run build-dev_heroku

CMD "npm run run-app"
