FROM ubuntu:18.04
RUN apt update && apt install -y nodejs && apt install -y npm

WORKDIR /var/www

COPY ./package*.json .
RUN npm install

COPY . .

EXPOSE 5000

ENV NODE_ENV=development
ENV HTTP_PROTOCOL=http
ENV PORT=5000
ENV DATABASE_URL=postgres://postgresUser:newPassword@postgres:5432/fargo-cards

RUN npm run build-dev_heroku

CMD [ "node", "./serverDist/index.js" ]
