version: "3.9"

services:
    ssr-app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - psql-container
        ports:
            - "5000:5000"
        env_file: ./dev.env
        networks:
            - main-networks
        restart: always

    postgres:
        image: postgres:12
        container_name: psql-container
        ports:
            - "5432:5432"
        env_file: ./dev.env
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgresUser
            POSTGRES_PASSWORD: newPassword
            POSTGRES_DB: fargo-cards
        networks:
            - main-networks
        restart: always

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.18
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - ./pgadmin-data:/var/lib/pgadmin
        depends_on:
            - psql-container
        networks:
            - main-networks
        restart: always

networks:
    main-networks:
        driver: bridge
